### ISSUE TITLE
can't sync -> s3 when not using us-east-1

### ISSUE THREAD

**Issue by earlh** [dmpetrov/dataversioncontrol#22]
must specify host for S3Connection; see discussion here
https://github.com/boto/boto/issues/621

and list of required hosts
http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by dmpetrov** [comment]
ha..., quite ugly. Should we translate the region in our code? us-east-1 --> s3.dualstack.us-east-1.amazonaws.com

**Comment by earlh** [comment]
fixed in WIP pr

**Comment by earlh** [comment]
#24
